services:
  eureka-server:
    build: services/eureka-server/.
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - shopping-network

  gateway:
    build: services/gateway/.
    container_name: gateway
    ports:
      - "8080:8080"
    networks:
      - shopping-network
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  product-service:
    build: services/product-service/.
    container_name: product-service
    ports:
      - "8081:8081"
    networks:
      - shopping-network
    depends_on:
      - eureka-server
      - gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

networks:
  shopping-network:
    driver: bridge